import { CTA } from "../sections/CTA";

const timelineSteps = [
  {
    step: "01",
    title: "Connect Your Wallet",
    description: "Open the Lace wallet extension for Midnight Network and connect it to our application. The wallet provides a pseudonymous identity without revealing personal information.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M21 12a2.25 2.25 0 00-2.25-2.25H15a3 3 0 11-6 0H5.25A2.25 2.25 0 003 12m18 0v6a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 18v-6m18 0V9M3 12V9m18 0a2.25 2.25 0 00-2.25-2.25H5.25A2.25 2.25 0 003 9m18 0V6a2.25 2.25 0 00-2.25-2.25H5.25A2.25 2.25 0 003 6v3" />
      </svg>
    ),
    detail: "Your wallet address is pseudonymous — it doesn't contain your name, email, or any personal identifiers.",
  },
  {
    step: "02",
    title: "Enter Financial Information",
    description: "Input your annual income and credit score into the application form. These values are processed entirely in your browser.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
      </svg>
    ),
    detail: "Your data is never sent to our servers. It stays in your browser's memory and is used only for proof generation.",
  },
  {
    step: "03",
    title: "Generate Zero-Knowledge Proof",
    description: "The application uses the Midnight proof server to generate a cryptographic proof that your data meets the eligibility criteria.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456zM16.894 20.567L16.5 21.75l-.394-1.183a2.25 2.25 0 00-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 001.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 001.423 1.423l1.183.394-1.183.394a2.25 2.25 0 00-1.423 1.423z" />
      </svg>
    ),
    detail: "The proof cryptographically demonstrates that your income and credit score meet thresholds — without revealing the actual values.",
  },
  {
    step: "04",
    title: "Wallet Signs Transaction",
    description: "Your Lace wallet signs the proof transaction, creating a cryptographic attestation that the proof is valid and was generated by you.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M17.25 6.75L22.5 12l-5.25 5.25m-10.5 0L1.5 12l5.25-5.25m7.5-3l-4.5 16.5" />
      </svg>
    ),
    detail: "The signature proves the proof came from a legitimate wallet without revealing your identity.",
  },
  {
    step: "05",
    title: "Blockchain Records Result",
    description: "The verified eligibility result is immutably recorded on the Midnight Network. Only the binary result (eligible/not) is stored — no financial data.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" d="M20.25 6.375c0 2.278-3.694 4.125-8.25 4.125S3.75 8.653 3.75 6.375m16.5 0c0-2.278-3.694-4.125-8.25-4.125S3.75 4.097 3.75 6.375m16.5 0v11.25c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125V6.375m16.5 0v3.75m-16.5-3.75v3.75m16.5 0v3.75C20.25 16.153 16.556 18 12 18s-8.25-1.847-8.25-4.125v-3.75m16.5 0c0 2.278-3.694 4.125-8.25 4.125s-8.25-1.847-8.25-4.125" />
      </svg>
    ),
    detail: "The blockchain record is permanent, transparent, and tamper-proof — anyone can verify the eligibility decision.",
  },
];

export function HowItWorksPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative overflow-hidden pt-36 pb-24 lg:pt-48 lg:pb-32">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_top_left,rgba(99,102,241,0.12),transparent_28%),radial-gradient(circle_at_top_right,rgba(34,211,238,0.08),transparent_24%)]" />
        <div className="container-page">
          <div className="mx-auto max-w-3xl rounded-[2rem] border border-white/15 bg-white/65 px-6 py-10 text-center shadow-[0_24px_90px_rgba(15,23,42,0.08)] backdrop-blur-xl lg:px-10 lg:py-14 dark:border-white/10 dark:bg-slate-950/55">
            <h1 className="text-hero text-balance text-gray-950 dark:text-white">
              How <span className="text-primary-600 dark:text-primary-400">zero-knowledge</span> verification works
            </h1>
            <p className="mt-6 text-hero-sub text-gray-600 dark:text-gray-300">
              Five simple steps to verify your loan eligibility — with complete privacy 
              at every stage. No financial data ever leaves your browser.
            </p>
          </div>
        </div>
      </section>

      {/* Timeline */}
      <section className="section-spacing relative overflow-hidden">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_center,rgba(99,102,241,0.08),transparent_40%)]" />
        <div className="container-page">
          <div className="mx-auto max-w-3xl">
            <div className="relative">
              {/* Vertical line */}
              <div className="absolute left-[39px] top-0 bottom-0 w-px bg-gradient-to-b from-indigo-300 via-cyan-300 to-pink-300 dark:from-indigo-700 dark:via-cyan-700 dark:to-pink-700" />

              <div className="space-y-12">
                {timelineSteps.map((step, i) => (
                  <div key={i} className="relative flex gap-8">
                    {/* Step indicator */}
                    <div className="relative z-10 flex flex-col items-center">
                      <div className="flex h-20 w-20 items-center justify-center rounded-[1.5rem] border border-white/15 bg-white/75 text-primary-600 shadow-[0_18px_50px_rgba(15,23,42,0.08)] backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/60 dark:text-cyan-300">
                        {step.icon}
                      </div>
                    </div>

                    {/* Content */}
                    <div className="flex-1 rounded-[1.75rem] border border-white/15 bg-white/70 p-8 shadow-[0_24px_80px_rgba(15,23,42,0.08)] backdrop-blur-xl dark:border-white/10 dark:bg-slate-950/60">
                      <div className="flex items-center gap-3 mb-3">
                        <span className="inline-flex rounded-full bg-gradient-to-r from-indigo-500 via-primary-500 to-cyan-500 px-3 py-1 text-xs font-bold tracking-[0.2em] text-white shadow-[0_12px_30px_rgba(79,70,229,0.18)]">STEP {step.step}</span>
                      </div>
                      <h3 className="text-xl font-semibold text-gray-950 dark:text-white">{step.title}</h3>
                      <p className="mt-3 text-body leading-relaxed text-gray-600 dark:text-gray-300">{step.description}</p>
                      <div className="mt-4 rounded-2xl bg-white/70 px-4 py-3 backdrop-blur-xl dark:bg-white/5">
                        <p className="text-caption text-primary-700 dark:text-cyan-300">
                          <span className="font-semibold">Privacy note:</span> {step.detail}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Summary */}
      <section className="section-spacing relative overflow-hidden">
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_bottom_right,rgba(34,211,238,0.08),transparent_28%)]" />
        <div className="container-page">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="section-heading">The result</h2>
            <p className="mt-4 text-body-lg text-gray-600 dark:text-gray-300">
              Your loan eligibility is verified and recorded on the Midnight Network — 
              without your income, credit score, or personal identity ever being exposed. 
              This is the future of private financial verification.
            </p>
          </div>
        </div>
      </section>

      <CTA />
    </>
  );
}
